/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_lib_TemplateSdk */
#include "MyPurchase.h"
#ifndef _Included_org_cocos2dx_lib_TemplateSdk
#define _Included_org_cocos2dx_lib_TemplateSdk
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cocos2dx_lib_TemplateSdk_PAY_RESULT_SUCCESS
#define org_cocos2dx_lib_TemplateSdk_PAY_RESULT_SUCCESS 0L
#undef org_cocos2dx_lib_TemplateSdk_PAY_RESULT_FAILED
#define org_cocos2dx_lib_TemplateSdk_PAY_RESULT_FAILED 1L
#undef org_cocos2dx_lib_TemplateSdk_PAY_RESULT_CANCEL
#define org_cocos2dx_lib_TemplateSdk_PAY_RESULT_CANCEL 2L
#undef org_cocos2dx_lib_TemplateSdk_PAY_RESULT_TIMEOUT
#define org_cocos2dx_lib_TemplateSdk_PAY_RESULT_TIMEOUT 3L
/*
 * Class:     org_cocos2dx_lib_TemplateSdk
 * Method:    onPurchase
 * Signature: (I)V
 */
	JNIEXPORT void JNICALL Java_org_cocos2dx_lib_TemplateSdk_onPurchase
		(JNIEnv *, jobject, jint ret)
	{
		MyPurchase::sharedPurchase()->onPayResult(ret);
	}

#ifdef __cplusplus
}
#endif
#endif
