/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "MyPurchase.h"
/* Header for class org_cocos2dx_lib_MiGuSdk */

#ifndef _Included_org_cocos2dx_lib_MiGuSdk
#define _Included_org_cocos2dx_lib_MiGuSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_lib_MiGuSdk
 * Method:    onPurchase
 * Signature: (I)V
 */
	JNIEXPORT void JNICALL Java_org_cocos2dx_lib_MiGuSdk_onPurchase
		(JNIEnv *, jobject, jint ret)
	{
		MyPurchase::sharedPurchase()->onPayResult(ret);
	}

#ifdef __cplusplus
}
#endif
#endif
