/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_lib_DongXinPush */

#ifndef _Included_org_cocos2dx_lib_DongXinPush
#define _Included_org_cocos2dx_lib_DongXinPush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_lib_DongXinPush
 * Method:    updateShangYongStatus
 * Signature: (Z)V
 */
	JNIEXPORT void JNICALL Java_org_cocos2dx_lib_DongXinPush_updateShangYongStatus
		(JNIEnv *, jobject, jboolean isBusiness)
	{
		GameBackEndState::theModel()->setBusinessMode(isBusiness);
	}

#ifdef __cplusplus
}
#endif
#endif
